/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as Game1Import } from './routes/game1'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const Game1Route = Game1Import.update({
  id: '/game1',
  path: '/game1',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/game1': {
      id: '/game1'
      path: '/game1'
      fullPath: '/game1'
      preLoaderRoute: typeof Game1Import
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/game1': typeof Game1Route
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/game1': typeof Game1Route
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/game1': typeof Game1Route
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/game1'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/game1'
  id: '__root__' | '/' | '/game1'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  Game1Route: typeof Game1Route
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  Game1Route: Game1Route,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/game1"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/game1": {
      "filePath": "game1.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
