/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as Round3Import } from './routes/round3'
import { Route as Round2Import } from './routes/round2'
import { Route as Round1Import } from './routes/round1'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const Round3Route = Round3Import.update({
  id: '/round3',
  path: '/round3',
  getParentRoute: () => rootRoute,
} as any)

const Round2Route = Round2Import.update({
  id: '/round2',
  path: '/round2',
  getParentRoute: () => rootRoute,
} as any)

const Round1Route = Round1Import.update({
  id: '/round1',
  path: '/round1',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/round1': {
      id: '/round1'
      path: '/round1'
      fullPath: '/round1'
      preLoaderRoute: typeof Round1Import
      parentRoute: typeof rootRoute
    }
    '/round2': {
      id: '/round2'
      path: '/round2'
      fullPath: '/round2'
      preLoaderRoute: typeof Round2Import
      parentRoute: typeof rootRoute
    }
    '/round3': {
      id: '/round3'
      path: '/round3'
      fullPath: '/round3'
      preLoaderRoute: typeof Round3Import
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/round1': typeof Round1Route
  '/round2': typeof Round2Route
  '/round3': typeof Round3Route
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/round1': typeof Round1Route
  '/round2': typeof Round2Route
  '/round3': typeof Round3Route
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/round1': typeof Round1Route
  '/round2': typeof Round2Route
  '/round3': typeof Round3Route
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/round1' | '/round2' | '/round3'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/round1' | '/round2' | '/round3'
  id: '__root__' | '/' | '/round1' | '/round2' | '/round3'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  Round1Route: typeof Round1Route
  Round2Route: typeof Round2Route
  Round3Route: typeof Round3Route
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  Round1Route: Round1Route,
  Round2Route: Round2Route,
  Round3Route: Round3Route,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/round1",
        "/round2",
        "/round3"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/round1": {
      "filePath": "round1.tsx"
    },
    "/round2": {
      "filePath": "round2.tsx"
    },
    "/round3": {
      "filePath": "round3.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
